// <auto-generated />
using Catalog.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Catalog.Persistence.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Catalog")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "Descripcion 1",
                            Name = "Producto 1",
                            Price = 1485m
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "Descripcion 2",
                            Name = "Producto 2",
                            Price = 304m
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "Descripcion 3",
                            Name = "Producto 3",
                            Price = 1347m
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "Descripcion 4",
                            Name = "Producto 4",
                            Price = 1346m
                        },
                        new
                        {
                            ProductId = 5,
                            Description = "Descripcion 5",
                            Name = "Producto 5",
                            Price = 201m
                        },
                        new
                        {
                            ProductId = 6,
                            Description = "Descripcion 6",
                            Name = "Producto 6",
                            Price = 399m
                        },
                        new
                        {
                            ProductId = 7,
                            Description = "Descripcion 7",
                            Name = "Producto 7",
                            Price = 233m
                        },
                        new
                        {
                            ProductId = 8,
                            Description = "Descripcion 8",
                            Name = "Producto 8",
                            Price = 533m
                        },
                        new
                        {
                            ProductId = 9,
                            Description = "Descripcion 9",
                            Name = "Producto 9",
                            Price = 612m
                        },
                        new
                        {
                            ProductId = 10,
                            Description = "Descripcion 10",
                            Name = "Producto 10",
                            Price = 492m
                        },
                        new
                        {
                            ProductId = 11,
                            Description = "Descripcion 11",
                            Name = "Producto 11",
                            Price = 1469m
                        },
                        new
                        {
                            ProductId = 12,
                            Description = "Descripcion 12",
                            Name = "Producto 12",
                            Price = 1416m
                        },
                        new
                        {
                            ProductId = 13,
                            Description = "Descripcion 13",
                            Name = "Producto 13",
                            Price = 1447m
                        },
                        new
                        {
                            ProductId = 14,
                            Description = "Descripcion 14",
                            Name = "Producto 14",
                            Price = 1318m
                        },
                        new
                        {
                            ProductId = 15,
                            Description = "Descripcion 15",
                            Name = "Producto 15",
                            Price = 1329m
                        },
                        new
                        {
                            ProductId = 16,
                            Description = "Descripcion 16",
                            Name = "Producto 16",
                            Price = 1249m
                        },
                        new
                        {
                            ProductId = 17,
                            Description = "Descripcion 17",
                            Name = "Producto 17",
                            Price = 256m
                        },
                        new
                        {
                            ProductId = 18,
                            Description = "Descripcion 18",
                            Name = "Producto 18",
                            Price = 951m
                        },
                        new
                        {
                            ProductId = 19,
                            Description = "Descripcion 19",
                            Name = "Producto 19",
                            Price = 697m
                        },
                        new
                        {
                            ProductId = 20,
                            Description = "Descripcion 20",
                            Name = "Producto 20",
                            Price = 742m
                        },
                        new
                        {
                            ProductId = 21,
                            Description = "Descripcion 21",
                            Name = "Producto 21",
                            Price = 1202m
                        },
                        new
                        {
                            ProductId = 22,
                            Description = "Descripcion 22",
                            Name = "Producto 22",
                            Price = 1404m
                        },
                        new
                        {
                            ProductId = 23,
                            Description = "Descripcion 23",
                            Name = "Producto 23",
                            Price = 329m
                        },
                        new
                        {
                            ProductId = 24,
                            Description = "Descripcion 24",
                            Name = "Producto 24",
                            Price = 1396m
                        },
                        new
                        {
                            ProductId = 25,
                            Description = "Descripcion 25",
                            Name = "Producto 25",
                            Price = 1468m
                        },
                        new
                        {
                            ProductId = 26,
                            Description = "Descripcion 26",
                            Name = "Producto 26",
                            Price = 1259m
                        },
                        new
                        {
                            ProductId = 27,
                            Description = "Descripcion 27",
                            Name = "Producto 27",
                            Price = 996m
                        },
                        new
                        {
                            ProductId = 28,
                            Description = "Descripcion 28",
                            Name = "Producto 28",
                            Price = 962m
                        },
                        new
                        {
                            ProductId = 29,
                            Description = "Descripcion 29",
                            Name = "Producto 29",
                            Price = 1465m
                        },
                        new
                        {
                            ProductId = 30,
                            Description = "Descripcion 30",
                            Name = "Producto 30",
                            Price = 1259m
                        },
                        new
                        {
                            ProductId = 31,
                            Description = "Descripcion 31",
                            Name = "Producto 31",
                            Price = 608m
                        },
                        new
                        {
                            ProductId = 32,
                            Description = "Descripcion 32",
                            Name = "Producto 32",
                            Price = 855m
                        },
                        new
                        {
                            ProductId = 33,
                            Description = "Descripcion 33",
                            Name = "Producto 33",
                            Price = 1398m
                        },
                        new
                        {
                            ProductId = 34,
                            Description = "Descripcion 34",
                            Name = "Producto 34",
                            Price = 283m
                        },
                        new
                        {
                            ProductId = 35,
                            Description = "Descripcion 35",
                            Name = "Producto 35",
                            Price = 228m
                        },
                        new
                        {
                            ProductId = 36,
                            Description = "Descripcion 36",
                            Name = "Producto 36",
                            Price = 729m
                        },
                        new
                        {
                            ProductId = 37,
                            Description = "Descripcion 37",
                            Name = "Producto 37",
                            Price = 813m
                        },
                        new
                        {
                            ProductId = 38,
                            Description = "Descripcion 38",
                            Name = "Producto 38",
                            Price = 1392m
                        },
                        new
                        {
                            ProductId = 39,
                            Description = "Descripcion 39",
                            Name = "Producto 39",
                            Price = 1354m
                        },
                        new
                        {
                            ProductId = 40,
                            Description = "Descripcion 40",
                            Name = "Producto 40",
                            Price = 963m
                        },
                        new
                        {
                            ProductId = 41,
                            Description = "Descripcion 41",
                            Name = "Producto 41",
                            Price = 691m
                        },
                        new
                        {
                            ProductId = 42,
                            Description = "Descripcion 42",
                            Name = "Producto 42",
                            Price = 545m
                        },
                        new
                        {
                            ProductId = 43,
                            Description = "Descripcion 43",
                            Name = "Producto 43",
                            Price = 706m
                        },
                        new
                        {
                            ProductId = 44,
                            Description = "Descripcion 44",
                            Name = "Producto 44",
                            Price = 172m
                        },
                        new
                        {
                            ProductId = 45,
                            Description = "Descripcion 45",
                            Name = "Producto 45",
                            Price = 596m
                        },
                        new
                        {
                            ProductId = 46,
                            Description = "Descripcion 46",
                            Name = "Producto 46",
                            Price = 740m
                        },
                        new
                        {
                            ProductId = 47,
                            Description = "Descripcion 47",
                            Name = "Producto 47",
                            Price = 1101m
                        },
                        new
                        {
                            ProductId = 48,
                            Description = "Descripcion 48",
                            Name = "Producto 48",
                            Price = 268m
                        },
                        new
                        {
                            ProductId = 49,
                            Description = "Descripcion 49",
                            Name = "Producto 49",
                            Price = 848m
                        },
                        new
                        {
                            ProductId = 50,
                            Description = "Descripcion 50",
                            Name = "Producto 50",
                            Price = 292m
                        },
                        new
                        {
                            ProductId = 51,
                            Description = "Descripcion 51",
                            Name = "Producto 51",
                            Price = 840m
                        },
                        new
                        {
                            ProductId = 52,
                            Description = "Descripcion 52",
                            Name = "Producto 52",
                            Price = 960m
                        },
                        new
                        {
                            ProductId = 53,
                            Description = "Descripcion 53",
                            Name = "Producto 53",
                            Price = 206m
                        },
                        new
                        {
                            ProductId = 54,
                            Description = "Descripcion 54",
                            Name = "Producto 54",
                            Price = 521m
                        },
                        new
                        {
                            ProductId = 55,
                            Description = "Descripcion 55",
                            Name = "Producto 55",
                            Price = 691m
                        },
                        new
                        {
                            ProductId = 56,
                            Description = "Descripcion 56",
                            Name = "Producto 56",
                            Price = 180m
                        },
                        new
                        {
                            ProductId = 57,
                            Description = "Descripcion 57",
                            Name = "Producto 57",
                            Price = 1475m
                        },
                        new
                        {
                            ProductId = 58,
                            Description = "Descripcion 58",
                            Name = "Producto 58",
                            Price = 1451m
                        },
                        new
                        {
                            ProductId = 59,
                            Description = "Descripcion 59",
                            Name = "Producto 59",
                            Price = 1377m
                        },
                        new
                        {
                            ProductId = 60,
                            Description = "Descripcion 60",
                            Name = "Producto 60",
                            Price = 441m
                        },
                        new
                        {
                            ProductId = 61,
                            Description = "Descripcion 61",
                            Name = "Producto 61",
                            Price = 902m
                        },
                        new
                        {
                            ProductId = 62,
                            Description = "Descripcion 62",
                            Name = "Producto 62",
                            Price = 770m
                        },
                        new
                        {
                            ProductId = 63,
                            Description = "Descripcion 63",
                            Name = "Producto 63",
                            Price = 568m
                        },
                        new
                        {
                            ProductId = 64,
                            Description = "Descripcion 64",
                            Name = "Producto 64",
                            Price = 853m
                        },
                        new
                        {
                            ProductId = 65,
                            Description = "Descripcion 65",
                            Name = "Producto 65",
                            Price = 1384m
                        },
                        new
                        {
                            ProductId = 66,
                            Description = "Descripcion 66",
                            Name = "Producto 66",
                            Price = 713m
                        },
                        new
                        {
                            ProductId = 67,
                            Description = "Descripcion 67",
                            Name = "Producto 67",
                            Price = 118m
                        },
                        new
                        {
                            ProductId = 68,
                            Description = "Descripcion 68",
                            Name = "Producto 68",
                            Price = 1264m
                        },
                        new
                        {
                            ProductId = 69,
                            Description = "Descripcion 69",
                            Name = "Producto 69",
                            Price = 1189m
                        },
                        new
                        {
                            ProductId = 70,
                            Description = "Descripcion 70",
                            Name = "Producto 70",
                            Price = 699m
                        },
                        new
                        {
                            ProductId = 71,
                            Description = "Descripcion 71",
                            Name = "Producto 71",
                            Price = 535m
                        },
                        new
                        {
                            ProductId = 72,
                            Description = "Descripcion 72",
                            Name = "Producto 72",
                            Price = 363m
                        },
                        new
                        {
                            ProductId = 73,
                            Description = "Descripcion 73",
                            Name = "Producto 73",
                            Price = 1096m
                        },
                        new
                        {
                            ProductId = 74,
                            Description = "Descripcion 74",
                            Name = "Producto 74",
                            Price = 1234m
                        },
                        new
                        {
                            ProductId = 75,
                            Description = "Descripcion 75",
                            Name = "Producto 75",
                            Price = 150m
                        },
                        new
                        {
                            ProductId = 76,
                            Description = "Descripcion 76",
                            Name = "Producto 76",
                            Price = 757m
                        },
                        new
                        {
                            ProductId = 77,
                            Description = "Descripcion 77",
                            Name = "Producto 77",
                            Price = 798m
                        },
                        new
                        {
                            ProductId = 78,
                            Description = "Descripcion 78",
                            Name = "Producto 78",
                            Price = 257m
                        },
                        new
                        {
                            ProductId = 79,
                            Description = "Descripcion 79",
                            Name = "Producto 79",
                            Price = 900m
                        },
                        new
                        {
                            ProductId = 80,
                            Description = "Descripcion 80",
                            Name = "Producto 80",
                            Price = 828m
                        },
                        new
                        {
                            ProductId = 81,
                            Description = "Descripcion 81",
                            Name = "Producto 81",
                            Price = 257m
                        },
                        new
                        {
                            ProductId = 82,
                            Description = "Descripcion 82",
                            Name = "Producto 82",
                            Price = 828m
                        },
                        new
                        {
                            ProductId = 83,
                            Description = "Descripcion 83",
                            Name = "Producto 83",
                            Price = 214m
                        },
                        new
                        {
                            ProductId = 84,
                            Description = "Descripcion 84",
                            Name = "Producto 84",
                            Price = 1272m
                        },
                        new
                        {
                            ProductId = 85,
                            Description = "Descripcion 85",
                            Name = "Producto 85",
                            Price = 518m
                        },
                        new
                        {
                            ProductId = 86,
                            Description = "Descripcion 86",
                            Name = "Producto 86",
                            Price = 1147m
                        },
                        new
                        {
                            ProductId = 87,
                            Description = "Descripcion 87",
                            Name = "Producto 87",
                            Price = 748m
                        },
                        new
                        {
                            ProductId = 88,
                            Description = "Descripcion 88",
                            Name = "Producto 88",
                            Price = 976m
                        },
                        new
                        {
                            ProductId = 89,
                            Description = "Descripcion 89",
                            Name = "Producto 89",
                            Price = 1091m
                        },
                        new
                        {
                            ProductId = 90,
                            Description = "Descripcion 90",
                            Name = "Producto 90",
                            Price = 147m
                        },
                        new
                        {
                            ProductId = 91,
                            Description = "Descripcion 91",
                            Name = "Producto 91",
                            Price = 754m
                        },
                        new
                        {
                            ProductId = 92,
                            Description = "Descripcion 92",
                            Name = "Producto 92",
                            Price = 862m
                        },
                        new
                        {
                            ProductId = 93,
                            Description = "Descripcion 93",
                            Name = "Producto 93",
                            Price = 115m
                        },
                        new
                        {
                            ProductId = 94,
                            Description = "Descripcion 94",
                            Name = "Producto 94",
                            Price = 1012m
                        },
                        new
                        {
                            ProductId = 95,
                            Description = "Descripcion 95",
                            Name = "Producto 95",
                            Price = 161m
                        },
                        new
                        {
                            ProductId = 96,
                            Description = "Descripcion 96",
                            Name = "Producto 96",
                            Price = 1421m
                        },
                        new
                        {
                            ProductId = 97,
                            Description = "Descripcion 97",
                            Name = "Producto 97",
                            Price = 1476m
                        },
                        new
                        {
                            ProductId = 98,
                            Description = "Descripcion 98",
                            Name = "Producto 98",
                            Price = 1353m
                        },
                        new
                        {
                            ProductId = 99,
                            Description = "Descripcion 99",
                            Name = "Producto 99",
                            Price = 288m
                        },
                        new
                        {
                            ProductId = 100,
                            Description = "Descripcion 100",
                            Name = "Producto 100",
                            Price = 1382m
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.Property<int>("ProductInStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductInStockId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.HasIndex("ProductInStockId");

                    b.ToTable("ProductsInStock");

                    b.HasData(
                        new
                        {
                            ProductInStockId = 1,
                            ProductId = 1,
                            Stock = 71
                        },
                        new
                        {
                            ProductInStockId = 2,
                            ProductId = 2,
                            Stock = 81
                        },
                        new
                        {
                            ProductInStockId = 3,
                            ProductId = 3,
                            Stock = 151
                        },
                        new
                        {
                            ProductInStockId = 4,
                            ProductId = 4,
                            Stock = 50
                        },
                        new
                        {
                            ProductInStockId = 5,
                            ProductId = 5,
                            Stock = 63
                        },
                        new
                        {
                            ProductInStockId = 6,
                            ProductId = 6,
                            Stock = 131
                        },
                        new
                        {
                            ProductInStockId = 7,
                            ProductId = 7,
                            Stock = 67
                        },
                        new
                        {
                            ProductInStockId = 8,
                            ProductId = 8,
                            Stock = 40
                        },
                        new
                        {
                            ProductInStockId = 9,
                            ProductId = 9,
                            Stock = 88
                        },
                        new
                        {
                            ProductInStockId = 10,
                            ProductId = 10,
                            Stock = 178
                        },
                        new
                        {
                            ProductInStockId = 11,
                            ProductId = 11,
                            Stock = 52
                        },
                        new
                        {
                            ProductInStockId = 12,
                            ProductId = 12,
                            Stock = 132
                        },
                        new
                        {
                            ProductInStockId = 13,
                            ProductId = 13,
                            Stock = 104
                        },
                        new
                        {
                            ProductInStockId = 14,
                            ProductId = 14,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 15,
                            ProductId = 15,
                            Stock = 61
                        },
                        new
                        {
                            ProductInStockId = 16,
                            ProductId = 16,
                            Stock = 61
                        },
                        new
                        {
                            ProductInStockId = 17,
                            ProductId = 17,
                            Stock = 135
                        },
                        new
                        {
                            ProductInStockId = 18,
                            ProductId = 18,
                            Stock = 148
                        },
                        new
                        {
                            ProductInStockId = 19,
                            ProductId = 19,
                            Stock = 34
                        },
                        new
                        {
                            ProductInStockId = 20,
                            ProductId = 20,
                            Stock = 90
                        },
                        new
                        {
                            ProductInStockId = 21,
                            ProductId = 21,
                            Stock = 20
                        },
                        new
                        {
                            ProductInStockId = 22,
                            ProductId = 22,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 23,
                            ProductId = 23,
                            Stock = 141
                        },
                        new
                        {
                            ProductInStockId = 24,
                            ProductId = 24,
                            Stock = 138
                        },
                        new
                        {
                            ProductInStockId = 25,
                            ProductId = 25,
                            Stock = 26
                        },
                        new
                        {
                            ProductInStockId = 26,
                            ProductId = 26,
                            Stock = 126
                        },
                        new
                        {
                            ProductInStockId = 27,
                            ProductId = 27,
                            Stock = 117
                        },
                        new
                        {
                            ProductInStockId = 28,
                            ProductId = 28,
                            Stock = 198
                        },
                        new
                        {
                            ProductInStockId = 29,
                            ProductId = 29,
                            Stock = 119
                        },
                        new
                        {
                            ProductInStockId = 30,
                            ProductId = 30,
                            Stock = 7
                        },
                        new
                        {
                            ProductInStockId = 31,
                            ProductId = 31,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 32,
                            ProductId = 32,
                            Stock = 58
                        },
                        new
                        {
                            ProductInStockId = 33,
                            ProductId = 33,
                            Stock = 160
                        },
                        new
                        {
                            ProductInStockId = 34,
                            ProductId = 34,
                            Stock = 161
                        },
                        new
                        {
                            ProductInStockId = 35,
                            ProductId = 35,
                            Stock = 142
                        },
                        new
                        {
                            ProductInStockId = 36,
                            ProductId = 36,
                            Stock = 142
                        },
                        new
                        {
                            ProductInStockId = 37,
                            ProductId = 37,
                            Stock = 49
                        },
                        new
                        {
                            ProductInStockId = 38,
                            ProductId = 38,
                            Stock = 27
                        },
                        new
                        {
                            ProductInStockId = 39,
                            ProductId = 39,
                            Stock = 171
                        },
                        new
                        {
                            ProductInStockId = 40,
                            ProductId = 40,
                            Stock = 16
                        },
                        new
                        {
                            ProductInStockId = 41,
                            ProductId = 41,
                            Stock = 36
                        },
                        new
                        {
                            ProductInStockId = 42,
                            ProductId = 42,
                            Stock = 181
                        },
                        new
                        {
                            ProductInStockId = 43,
                            ProductId = 43,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 44,
                            ProductId = 44,
                            Stock = 116
                        },
                        new
                        {
                            ProductInStockId = 45,
                            ProductId = 45,
                            Stock = 185
                        },
                        new
                        {
                            ProductInStockId = 46,
                            ProductId = 46,
                            Stock = 48
                        },
                        new
                        {
                            ProductInStockId = 47,
                            ProductId = 47,
                            Stock = 10
                        },
                        new
                        {
                            ProductInStockId = 48,
                            ProductId = 48,
                            Stock = 43
                        },
                        new
                        {
                            ProductInStockId = 49,
                            ProductId = 49,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 50,
                            ProductId = 50,
                            Stock = 178
                        },
                        new
                        {
                            ProductInStockId = 51,
                            ProductId = 51,
                            Stock = 140
                        },
                        new
                        {
                            ProductInStockId = 52,
                            ProductId = 52,
                            Stock = 81
                        },
                        new
                        {
                            ProductInStockId = 53,
                            ProductId = 53,
                            Stock = 160
                        },
                        new
                        {
                            ProductInStockId = 54,
                            ProductId = 54,
                            Stock = 47
                        },
                        new
                        {
                            ProductInStockId = 55,
                            ProductId = 55,
                            Stock = 150
                        },
                        new
                        {
                            ProductInStockId = 56,
                            ProductId = 56,
                            Stock = 61
                        },
                        new
                        {
                            ProductInStockId = 57,
                            ProductId = 57,
                            Stock = 140
                        },
                        new
                        {
                            ProductInStockId = 58,
                            ProductId = 58,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 59,
                            ProductId = 59,
                            Stock = 24
                        },
                        new
                        {
                            ProductInStockId = 60,
                            ProductId = 60,
                            Stock = 136
                        },
                        new
                        {
                            ProductInStockId = 61,
                            ProductId = 61,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 62,
                            ProductId = 62,
                            Stock = 69
                        },
                        new
                        {
                            ProductInStockId = 63,
                            ProductId = 63,
                            Stock = 121
                        },
                        new
                        {
                            ProductInStockId = 64,
                            ProductId = 64,
                            Stock = 80
                        },
                        new
                        {
                            ProductInStockId = 65,
                            ProductId = 65,
                            Stock = 177
                        },
                        new
                        {
                            ProductInStockId = 66,
                            ProductId = 66,
                            Stock = 194
                        },
                        new
                        {
                            ProductInStockId = 67,
                            ProductId = 67,
                            Stock = 171
                        },
                        new
                        {
                            ProductInStockId = 68,
                            ProductId = 68,
                            Stock = 142
                        },
                        new
                        {
                            ProductInStockId = 69,
                            ProductId = 69,
                            Stock = 68
                        },
                        new
                        {
                            ProductInStockId = 70,
                            ProductId = 70,
                            Stock = 118
                        },
                        new
                        {
                            ProductInStockId = 71,
                            ProductId = 71,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 72,
                            ProductId = 72,
                            Stock = 107
                        },
                        new
                        {
                            ProductInStockId = 73,
                            ProductId = 73,
                            Stock = 177
                        },
                        new
                        {
                            ProductInStockId = 74,
                            ProductId = 74,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 75,
                            ProductId = 75,
                            Stock = 53
                        },
                        new
                        {
                            ProductInStockId = 76,
                            ProductId = 76,
                            Stock = 38
                        },
                        new
                        {
                            ProductInStockId = 77,
                            ProductId = 77,
                            Stock = 192
                        },
                        new
                        {
                            ProductInStockId = 78,
                            ProductId = 78,
                            Stock = 25
                        },
                        new
                        {
                            ProductInStockId = 79,
                            ProductId = 79,
                            Stock = 152
                        },
                        new
                        {
                            ProductInStockId = 80,
                            ProductId = 80,
                            Stock = 178
                        },
                        new
                        {
                            ProductInStockId = 81,
                            ProductId = 81,
                            Stock = 115
                        },
                        new
                        {
                            ProductInStockId = 82,
                            ProductId = 82,
                            Stock = 74
                        },
                        new
                        {
                            ProductInStockId = 83,
                            ProductId = 83,
                            Stock = 183
                        },
                        new
                        {
                            ProductInStockId = 84,
                            ProductId = 84,
                            Stock = 141
                        },
                        new
                        {
                            ProductInStockId = 85,
                            ProductId = 85,
                            Stock = 67
                        },
                        new
                        {
                            ProductInStockId = 86,
                            ProductId = 86,
                            Stock = 119
                        },
                        new
                        {
                            ProductInStockId = 87,
                            ProductId = 87,
                            Stock = 98
                        },
                        new
                        {
                            ProductInStockId = 88,
                            ProductId = 88,
                            Stock = 113
                        },
                        new
                        {
                            ProductInStockId = 89,
                            ProductId = 89,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 90,
                            ProductId = 90,
                            Stock = 81
                        },
                        new
                        {
                            ProductInStockId = 91,
                            ProductId = 91,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 92,
                            ProductId = 92,
                            Stock = 35
                        },
                        new
                        {
                            ProductInStockId = 93,
                            ProductId = 93,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 94,
                            ProductId = 94,
                            Stock = 34
                        },
                        new
                        {
                            ProductInStockId = 95,
                            ProductId = 95,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 96,
                            ProductId = 96,
                            Stock = 167
                        },
                        new
                        {
                            ProductInStockId = 97,
                            ProductId = 97,
                            Stock = 60
                        },
                        new
                        {
                            ProductInStockId = 98,
                            ProductId = 98,
                            Stock = 137
                        },
                        new
                        {
                            ProductInStockId = 99,
                            ProductId = 99,
                            Stock = 139
                        },
                        new
                        {
                            ProductInStockId = 100,
                            ProductId = 100,
                            Stock = 191
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.HasOne("Catalog.Domain.Product", null)
                        .WithOne("Stock")
                        .HasForeignKey("Catalog.Domain.ProductInStock", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Navigation("Stock");
                });
#pragma warning restore 612, 618
        }
    }
}
